name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.local/share/virtualenvs
            target/
          key: ${{ runner.os }}-cache
      - name: Run script
        run: ./.github/workflows/hooks/pre-prepare-release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_VERSION: 2.0.0
          NEXT_VERSION: 999-SNAPSHOT
